### ISSUE TITLE
OpenIGTLink header version

### ISSUE THREAD

**Issue by drouin-simon** [IGSIO/OpenIGTLinkIO#58]
Hi all,

Running into some problems with Ole and Geir here at project week. The handshaking process to determine the header version when using IO is something we seem to have overlooked. 

The intended behaviour in Plus is that it uses the highest header version found in the messages it receives. But it doesn't work. Different parts of Plus seem to be modifying different instances of the class PlusIgtlClientInfo which results in always using the default header version. Even if it did work, this behaviour is problematic. When a client connects, the server starts sending messages right away, but will only start sending messages with the header version required by the client once the first client message reaches the server. 

We need a handshaking mechanism to agree on a common header version between the client and the server from the start. The question is whether the handshaking should be implemented at the level of OpenIGTLink or in IO. I, Ole and Geir lean more towards OpenIGTLink.

What do you think?

**Comment by adamrankin** [comment]
Andras and I talked about this a while ago. Major points are:

- OpenIGTLink is a very lightweight protocol, introduction of v2 header made things more complicated
- Backwards compatibility is very important
- Handshake mechanism would not be backwards compatible
- Application level behaviour is the least impactful to others

So, Plus is supposed to keep track of the highest header version ever received from a client, and respond with that header version. If it's not doing that, it's a bug!

Our vision was that clients would send v1, v2, v3, ...vX STATUS messages until it didn't receive a reply, and thus know the highest capability of the server.

It is asynchronous handshaking at the application level. I am open to revisiting the discussion.

Tagging @lassoan

**Comment by olevs** [comment]
Yes, there seems to be a bug in PLUS, never sending back v2 headers. I also tried to set ClientHeaderVersion in the PLUS config file, but that won't work either. The only way I find to make PLUS give med header v2 messages is to hardcode this in the PlusIgtlClientInfo constructor: ClientHeaderVersion(IGTL_HEADER_VERSION_2). We cannot seem to find where the bug is located in PLUS, but you may have more success as you are more familiar with the code base.

The handshaking could be made to be kind of backwards compatible. Let's say this is implemented in OpenIGTLink v4. If the other end don't answer to the handshaking, you know it uses OpenIGTLink < 4 (This can default to v1).

If it is out of the question to implement this in OpenIGTLinkIO, it could of course be implemented in OpenIGTLinkIO in the way you describe, but I think we first should consider doing it in OpenIGTLink. Another option is to implement this in OpenIGTLinkIO first, and then move the functionality to OpenIGTLink at a later time.

**Comment by olevs** [comment]
I have tried to get OpenIGTLinkIO to send OpenIGTLink messages with header version 2, but as it still won't make PLUS send header version 2, I haven't made any pull request for this.

**Comment by adamrankin** [comment]
Bug report here
https://github.com/PlusToolkit/PlusLib/issues/374

I'll work on that today.

**Comment by olevs** [comment]
That's great. I just made another pull request in PlusLib for the OpenIGTLinkIO ultrasound sector meta information: https://github.com/PlusToolkit/PlusLib/pull/375

**Comment by adamrankin** [comment]
I can confirm that PlusServer switches to sending the highest known received header version. Can you show me how you get the undesired behavior?

**Comment by adamrankin** [comment]
That being said, some messages are hardcoded to be sent as V1 because they are V1 era messages. I am changing this to send the highest known version always.

**Comment by adamrankin** [comment]
see https://github.com/PlusToolkit/PlusLib/pull/376

**Comment by adamrankin** [comment]
Plus is correctly recording the highest possible header version a client can support, but only sent the header version according to the IGTL spec.

So, even though a client may have been v2, it would (for example) send IMAGE messages as v1 messages because IMAGE was part of the v1 header. 

PR https://github.com/PlusToolkit/PlusLib/pull/376 changes this behaviour and now IMAGE (and all messages) messages are sent with v2 headers.

**Comment by drouin-simon** [comment]
Thanks Adam! 

There is a piece of code that feels suspicious to me in Plus (vtkPlusOpenIGTLinkServer.cxx, line 566):

`if (headerMsg->GetHeaderVersion() > client->ClientInfo.GetClientHeaderVersion())
{
         client->ClientInfo.SetClientHeaderVersion(std::min<int>(self->GetIGTLProtocolVersion(), headerMsg->GetHeaderVersion()));
}`

It seems to confuse protocol version (3) and header version (2).

**Comment by adamrankin** [comment]
Hey, good catch. Although it will still work, that's not as intended!
